# Generated by Django 3.1.7 on 2021-03-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='equipamentos.equipamento')),
            ],
        ),
    ]
