# Generated by Django 3.2 on 2021-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_instrument',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
