# Generated by Django 3.1.7 on 2021-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
