# Generated by Django 3.1.7 on 2021-04-07 18:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20210407_1833'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='end_date must be after start_date',
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gt', django.db.models.expressions.F('start_date')), _connector='OR'), name='end_date must be after start_date'),
        ),
    ]
