# Generated by Django 3.1.7 on 2021-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço por dia')),
                ('categorias', models.ManyToManyField(related_name='equipamentos', to='categorias.Categoria')),
            ],
        ),
    ]
