# Generated by Django 3.1.7 on 2021-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('equipamentos', '0002_auto_20210405_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='equipamentos', to='categorias.Categoria'),
        ),
    ]
