# Generated by Django 3.2 on 2021-04-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_equipamento_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='name',
            new_name='title',
        ),
    ]
