# Generated by Django 3.1.7 on 2021-03-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='tmp', max_length=255),
            preserve_default=False,
        ),
    ]
